### ISSUE TITLE
Error in running prepare_images.py

### ISSUE THREAD

**Issue by park9673** [drakelevy/ESPCN-TensorFlow#2]
I'm having an error like the following.

  File "prepare_images.py", line 37, in prepare_images
    lr_image = blurred[::ratio,::ratio,:]

How can I fix it?

**Comment by scalerhyme** [comment]
get the same error 'NameError: global name 'blurred' is not defined'

**Comment by kmh93** [comment]
l read the code,and i think the the author maybe forget to write  the downsumpling function
